name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
    - name: Build with Gradle
      run: |
        cd ./AndroidStudioProject
        chmod +x ./gradlew
        ./gradlew build
    - name: Debug print
      run: find .
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@7b7aa264d83dc58691451798b4d117d53d21edfe
      with:
        scan-type: 'fs'
        scan-ref: '.'
        artifact-type: 'jar'
        severity: 'CRITICAL,HIGH,MEDIUM,LOW'
        output: 'trivy-results.sarif'
    - name: Upload Trivy results to GitHub Code Scanning
      uses: github/codeql-action/upload-sarif@v3
      if: always() # Run even if the Trivy step failed
      with:
        sarif_file: trivy-results.sarif 
